export const FurnitureList = [
    {
      id: 1,
      title: "Grey chair",
      img: "../public/img/chairs/chair 1.jpeg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Chairs",
      price: "49.99",
    },
    {
      id: 2,
      title: "White chair",
      img: "../public/img/chairs/chair 2.jpeg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Chairs",
      price: "79.82",
    },
    {
      id: 3,
      title: "Dark chair",
      img: "../public/img/chairs/chair 3.jpeg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Chairs",
      price: "20.55",
    },
    {
      id: 4,
      title: "Bright chair",
      img: "../public/img/chairs/chair 4.jpeg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Chairs",
      price: "45",
    },
    {
      id: 5,
      title: "Sofa light",
      img: "../public/img/light/light 1.jpeg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Lights",
      price: "15.50",
    },
    {
      id: 6,
      title: "Loft light",
      img: "../public/img/light/light 2.jpeg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Lights",
      price: "120",
    },
    {
      id: 7,
      title: "Dinner table light",
      img: "../public/img/light/light 3.jpeg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Lights",
      price: "49.99",
    },
    {
      id: 8,
      title: "Water lily light",
      img: "../public/img/light/light 4.webp",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Lights",
      price: "20.15",
    },
    {
      id: 9,
      title: "Sofa light",
      img: "../public/img/light/light 5.jpeg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Lights",
      price: "30.15",
    },
    {
      id: 10,
      title: "Blue sofa",
      img: "../public/img/sofa/sofa 1.jpeg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Sofas",
      price: "120.15",
    },
    {
      id: 11,
      title: "Grey sofa",
      img: "../public/img/sofa/sofa 2.jpeg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Lights",
      price: "100",
    },
    {
      id: 12,
      title: "Grey little sofa",
      img: "../public/img/sofa/sofa 3.jpeg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Lights",
      price: "70.23",
    },
    {
      id: 13,
      title: "Long sofa",
      img: "../public/img/sofa/sofa 4.jpeg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Lights",
      price: "200.20",
    },
    {
      id: 14,
      title: "Modrian table",
      img: "../public/img/tables/table 1.jpeg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Tables",
      price: "120.30",
    },
    {
      id: 15,
      title: "White & wood table",
      img: "../public/img/tables/table 2.jpeg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Tables",
      price: "80.30",
    },
    {
      id: 16,
      title: "Thin wood table",
      img: "../public/img/tables/table 3.avif",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Tables",
      price: "80.30",
    },
    {
      id: 15,
      title: "Oval marble table",
      img: "../public/img/tables/table 4.jpeg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti!",
      category: "Tables",
      price: "180.40",
    },

]


